name: mytho_novel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.11
  shared_preferences: ^2.2.2
  mongo_dart: ^0.10.4
  dart_jsonwebtoken: ^2.17.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
          
  assets:
    - assets/
    - assets/images/splash_logo.png
    - assets/images/flag.png
    - assets/images/flagg.png